version: '3.8'

networks:
  host:
    name: host
    external: true

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    networks:
<<<<<<< HEAD
      - main
      - host
=======
      - host
>>>>>>> 7304c91 (Remove `main` network from nginx)
