version: '3.8'

services:
  backend:
    build: ./backend/.
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    ports:
     - "3001:3001"
    environment:
      - PathBase=/api
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
      - ConnectionStrings__Database=mongodb://mongodb:mongodb@mongodb
      - ConnectionStrings__Redis=redis:6379
      - osuApi__ClientId=
      - osuApi__ClientSecret=
      - osuApi__CallbackUrl=http://localhost:8080/OAuth
    volumes:
      - ./logs:/app/logs

  frontend:
    build: ./frontend/.
    ports:
     - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=circleforms
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db