version: '3.8'

services:
  backend:
    build: ./backend/.
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      - PathBase=/api
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:3001
      - ConnectionStrings__Database=mongodb://mongodb:mongodb@mongodb
      - ConnectionStrings__Redis=redis:6379,allowAdmin=true
      - osuApi__ClientId=
      - osuApi__ClientSecret=
      - osuApi__CallbackUrl=/oauth/callback
    volumes:
      - ./logs/backend:/app/logs
      - ./keys:/root/.aspnet/DataProtection-Keys

  frontend:
    build: ./frontend/.
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./logs/frontend:/app/logs
      - ./logs/frontend/npm:/root/.npm/_logs

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis:/data
      - ./logs/redis:/var/log/redis

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=circleforms
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./db:/data/db
      - ./logs/mongo:/var/log/mongodb
